name: Pylint badge

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Silleellie/pylint-github-action@v1
        with:
          package-path: .
          python-version: "3.10"
          requirements-path: requirements.txt